-- Create lists table
CREATE TABLE IF NOT EXISTS public.lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id UUID NOT NULL REFERENCES public.spaces(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add list_id to tasks
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS list_id BIGINT REFERENCES public.lists(id) ON DELETE SET NULL;

-- Enable RLS
ALTER TABLE public.lists ENABLE ROW LEVEL SECURITY;

-- Create policies for lists
DROP POLICY IF EXISTS "Enable access for space members" ON public.lists;
CREATE POLICY "Enable access for space members" ON public.lists FOR ALL TO authenticated USING (
  public.is_space_member(space_id)
  OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

-- Grant permissions
GRANT ALL ON TABLE public.lists TO authenticated;
GRANT ALL ON TABLE public.lists TO service_role;
